### ISSUE TITLE
where are training set and the trained models?

### ISSUE THREAD

**Issue by amrhamedp** [idrori/cu-tsp#10]
The repository doesn't have the training set mentioned in the article. I am also not sure if the models are available. The present pickle files are just predictions.

**Comment by idrori** [comment]
https://drive.google.com/drive/u/0/folders/1QOugOGUY83H4q-7zVMoOW-DM1xby8sAg

**Comment by tr1pzz** [comment]
Thanks for sharing the dataset!
Are there any pretrained models available?

**Comment by tr1pzz** [comment]
Update, I just realized there are .pkl files in the model folder, I'm assuming they are the trained models, will investigate!
