### ISSUE TITLE
Comparison between various reconstruction options

### ISSUE THREAD

**Issue by tr1pzz** [idrori/cu-tsp#11]
In [the eval script](https://github.com/idrori/cu-tsp/blob/master/reconstruction/eval.py) there seem to be various ways of reconstructing the full atom protein coordinates (_distance_and_torsion,  torsion_only_comparison, distance_only_). The _distance_and_torsion_ function has an external java-based dependency.

I have a few questions:
- Do you have comparisons between these different methods in terms of final structural accuracy?
- Could you give a link to the external java-based dependency? I can't find this anywhere using Google
- The _build_fullatom_from_distance_ function uses "PeptideBuilderCoords" --> where can I find this dependency?

**Comment by idrori** [comment]
Full atom is reconstructed from backbone coordinates by energy minimization:
https://github.com/idrori/cu-tsp/tree/master/external/meshi9.36.2_light
